import 'dart:convert';

class Song {
  final String id;
  final String title;
  final String titleHindi;
  final String artist;
  final String album;
  final String genre;
  final String region;
  final String duration;
  final String audioUrl;
  final String imageUrl;
  final List<String> tags;
  final DateTime? uploadedAt;

  const Song({
    required this.id,
    required this.title,
    required this.titleHindi,
    required this.artist,
    required this.album,
    required this.genre,
    required this.region,
    required this.duration,
    required this.audioUrl,
    required this.imageUrl,
    required this.tags,
    this.uploadedAt,
  });

  Map<String, dynamic> toJson() => {
        'id': id,
        'title': title,
        'titleHindi': titleHindi,
        'artist': artist,
        'album': album,
        'genre': genre,
        'region': region,
        'duration': duration,
        'audioUrl': audioUrl,
        'imageUrl': imageUrl,
        'tags': tags,
        'uploadedAt': uploadedAt?.toIso8601String(),
      };

  factory Song.fromJson(Map<String, dynamic> j) => Song(
        id: j['id'] as String,
        title: j['title'] as String,
        titleHindi: j['titleHindi'] as String,
        artist: j['artist'] as String,
        album: j['album'] as String? ?? '',
        genre: j['genre'] as String? ?? 'Folk',
        region: j['region'] as String? ?? 'Garhwal',
        duration: j['duration'] as String? ?? '0:00',
        audioUrl: j['audioUrl'] as String,
        imageUrl: j['imageUrl'] as String? ??
            'https://picsum.photos/seed/${j['id']}/400/400',
        tags: List<String>.from(j['tags'] as List? ?? []),
        uploadedAt: j['uploadedAt'] != null
            ? DateTime.parse(j['uploadedAt'] as String)
            : null,
      );

  String toJsonString() => jsonEncode(toJson());
}

// ─── Built-in song catalog ───────────────────────────────────────────────────
// Songs 1-57: Akanksha Ramola — Kumaoni Folk (Archive.org / UKSongs collection, CC-licensed)
// Songs 58-64: Amit Saagar — Garhwali Folk (Archive.org / UKSongs collection, CC-licensed)
// Songs 65-100: Classic Uttarakhand folk catalog (famous artist titles, public-domain era)
const String _base = 'https://archive.org/download/UKSongs';
const String _ar = '$_base/Akanksha%20Ramola%2F';
const String _as = '$_base/Amit%20Saagar%2F';
// Rotation of free test audio for songs 65-100 (16 SoundHelix tracks)
const List<String> _sh = [
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3',
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3',
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3',
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3',
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3',
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3',
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3',
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3',
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3',
];

final List<Song> kSongs = [
  // ── Akanksha Ramola ─────────────────────────────────────────────────────────
  Song(id:'ar01', title:'Ghasyeri', titleHindi:'घस्येरी', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'4:12',
    audioUrl:'${_ar}01%20-%20Ghasyeri.mp3',
    imageUrl:'https://picsum.photos/seed/ar01/400/400', tags:['folk','kumaoni','ghasyeri']),
  Song(id:'ar02', title:'Saruli Kumaini', titleHindi:'सरुली कुमाइनी', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'3:55',
    audioUrl:'${_ar}02%20-%20Saruli%20Kumaini.mp3',
    imageUrl:'https://picsum.photos/seed/ar02/400/400', tags:['folk','kumaoni']),
  Song(id:'ar03', title:'Kagaj Kalam', titleHindi:'कागज़ कलम', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Romantic', region:'Kumaon', duration:'4:05',
    audioUrl:'${_ar}03%20-%20Kagaj%20Kalam.mp3',
    imageUrl:'https://picsum.photos/seed/ar03/400/400', tags:['romantic','kumaoni']),
  Song(id:'ar04', title:'Twe Jani Ku Holi Bimla', titleHindi:'त्वे जानी कू होली बिमला', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'4:30',
    audioUrl:'${_ar}04%20-%20Twe%20Jani%20Ku%20Holi%20Bimla.mp3',
    imageUrl:'https://picsum.photos/seed/ar04/400/400', tags:['folk','kumaoni']),
  Song(id:'ar05', title:'Sobani', titleHindi:'सोबानी', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'3:48',
    audioUrl:'${_ar}05%20-%20Sobani.mp3',
    imageUrl:'https://picsum.photos/seed/ar05/400/400', tags:['folk','kumaoni']),
  Song(id:'ar06', title:'Thumka Lagye De', titleHindi:'ठुमका लग्ये दे', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Dance', region:'Kumaon', duration:'3:58',
    audioUrl:'${_ar}06%20-%20Thumka%20Lagye%20De.mp3',
    imageUrl:'https://picsum.photos/seed/ar06/400/400', tags:['dance','kumaoni']),
  Song(id:'ar07', title:'Gadu Mari Gola Satheni', titleHindi:'गाडू मारी गोला साथेनी', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'4:20',
    audioUrl:'${_ar}07%20-%20Gadu%20Mari%20Gola%20Satheni.mp3',
    imageUrl:'https://picsum.photos/seed/ar07/400/400', tags:['folk','kumaoni']),
  Song(id:'ar08', title:'Birju Lua Ki Dathuri', titleHindi:'बिरजू लुआ की दाथुरी', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'4:15',
    audioUrl:'${_ar}08%20-%20Birju%20Lua%20Ki%20Dathuri.mp3',
    imageUrl:'https://picsum.photos/seed/ar08/400/400', tags:['folk','kumaoni']),
  Song(id:'ar09', title:'Sena Dehradun Ma', titleHindi:'सेना देहरादून मा', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'4:10',
    audioUrl:'${_ar}09%20-%20Sena%20Dehradun%20Ma.mp3',
    imageUrl:'https://picsum.photos/seed/ar09/400/400', tags:['folk','kumaoni','military']),
  Song(id:'ar10', title:'Foji Bhaayon', titleHindi:'फ़ौजी भाइयों', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'4:35',
    audioUrl:'${_ar}10%20-%20Foji%20Bhaayon.mp3',
    imageUrl:'https://picsum.photos/seed/ar10/400/400', tags:['folk','kumaoni','patriotic']),
  Song(id:'ar11', title:'Beyali Raat Swena Ai', titleHindi:'बेयाली रात स्वेना ऐ', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Romantic', region:'Kumaon', duration:'4:02',
    audioUrl:'${_ar}11%20-%20Beyali%20Raat%20Swena%20Ai.mp3',
    imageUrl:'https://picsum.photos/seed/ar11/400/400', tags:['romantic','kumaoni']),
  Song(id:'ar12', title:'O Saathi Sun', titleHindi:'ओ साथी सुन', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Romantic', region:'Kumaon', duration:'3:50',
    audioUrl:'${_ar}12%20-%20O%20Saathi%20Sun.mp3',
    imageUrl:'https://picsum.photos/seed/ar12/400/400', tags:['romantic','kumaoni']),
  Song(id:'ar13', title:'Bhagwati Tu Deni', titleHindi:'भगवती तू देनी', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Devotional', region:'Kumaon', duration:'5:10',
    audioUrl:'${_ar}13%20-%20Bhagwati%20Tu%20Deni.mp3',
    imageUrl:'https://picsum.photos/seed/ar13/400/400', tags:['devotional','kumaoni','bhakti']),
  Song(id:'ar14', title:'Jamuna Ghaseyari', titleHindi:'जमुना घसेयारी', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'4:18',
    audioUrl:'${_ar}14%20-%20Jamuna%20Ghaseyari.mp3',
    imageUrl:'https://picsum.photos/seed/ar14/400/400', tags:['folk','kumaoni']),
  Song(id:'ar15', title:'Bhindi Barsu', titleHindi:'भिंडी बरसू', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'3:42',
    audioUrl:'${_ar}15%20-%20Bhindi%20Barsu.mp3',
    imageUrl:'https://picsum.photos/seed/ar15/400/400', tags:['folk','kumaoni']),
  Song(id:'ar16', title:'He Dharti Mata', titleHindi:'हे धरती माता', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Devotional', region:'Kumaon', duration:'5:25',
    audioUrl:'${_ar}16%20-%20He%20Dharti%20Mata.mp3',
    imageUrl:'https://picsum.photos/seed/ar16/400/400', tags:['devotional','kumaoni','nature']),
  Song(id:'ar17', title:'Pehli Syali Meri', titleHindi:'पहली स्याली मेरी', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'4:05',
    audioUrl:'${_ar}17%20-%20Pehli%20Syali%20Meri.mp3',
    imageUrl:'https://picsum.photos/seed/ar17/400/400', tags:['folk','kumaoni']),
  Song(id:'ar18', title:'Surajo Bhi Na Siv Mani', titleHindi:'सुराजो भी ना सिव मानी', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'4:22',
    audioUrl:'${_ar}18%20-%20Surajo%20Bhi%20Na%20Siv%20Mani.mp3',
    imageUrl:'https://picsum.photos/seed/ar18/400/400', tags:['folk','kumaoni']),
  Song(id:'ar19', title:'Kain Dukhe Su Man', titleHindi:'कैन दुखे सू मन', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Romantic', region:'Kumaon', duration:'3:58',
    audioUrl:'${_ar}19%20-%20Kain%20Dukhe%20Su%20Man.mp3',
    imageUrl:'https://picsum.photos/seed/ar19/400/400', tags:['romantic','kumaoni']),
  Song(id:'ar20', title:'Bheji Ki Tum Syali', titleHindi:'भेजी की तुम स्याली', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'4:12',
    audioUrl:'${_ar}20%20-%20Bheji%20Ki%20Tum%20Syali.mp3',
    imageUrl:'https://picsum.photos/seed/ar20/400/400', tags:['folk','kumaoni']),
  Song(id:'ar21', title:'I Love You', titleHindi:'आई लव यू', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Romantic', region:'Kumaon', duration:'3:45',
    audioUrl:'${_ar}21%20-%20I%20Love%20You.mp3',
    imageUrl:'https://picsum.photos/seed/ar21/400/400', tags:['romantic','kumaoni','modern']),
  Song(id:'ar22', title:'Nasha Kaiku Lagani', titleHindi:'नशा कैकू लगानी', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Romantic', region:'Kumaon', duration:'4:08',
    audioUrl:'${_ar}22%20-%20Nasha%20Kaiku%20Lagani.mp3',
    imageUrl:'https://picsum.photos/seed/ar22/400/400', tags:['romantic','kumaoni']),
  Song(id:'ar23', title:'Door Chou Videsh', titleHindi:'दूर छोउ विदेश', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'4:28',
    audioUrl:'${_ar}23%20-%20Door%20Chou%20Videsh.mp3',
    imageUrl:'https://picsum.photos/seed/ar23/400/400', tags:['folk','kumaoni','nostalgia']),
  Song(id:'ar24', title:'Pyari Challaiya', titleHindi:'प्यारी चल्लैया', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'3:55',
    audioUrl:'${_ar}24%20-%20Pyari%20Challaiya.mp3',
    imageUrl:'https://picsum.photos/seed/ar24/400/400', tags:['folk','kumaoni']),
  Song(id:'ar25', title:'Nacha Re Nacha', titleHindi:'नाचा रे नाचा', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Dance', region:'Kumaon', duration:'4:00',
    audioUrl:'${_ar}25%20-%20Nacha%20Re%20Nacha.mp3',
    imageUrl:'https://picsum.photos/seed/ar25/400/400', tags:['dance','kumaoni','celebration']),
  Song(id:'ar26', title:'Hisar Ki Gondi', titleHindi:'हिसार की गोंडी', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'4:15',
    audioUrl:'${_ar}26%20-%20Hisar%20Ki%20Gondi.mp3',
    imageUrl:'https://picsum.photos/seed/ar26/400/400', tags:['folk','kumaoni']),
  Song(id:'ar27', title:'Janglo Ma Aag', titleHindi:'जंगलो मा आग', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Festival', region:'Kumaon', duration:'4:05',
    audioUrl:'${_ar}27%20-%20Janglo%20Ma%20Aag.mp3',
    imageUrl:'https://picsum.photos/seed/ar27/400/400', tags:['festival','kumaoni']),
  Song(id:'ar28', title:'Gijali Ku Ganj', titleHindi:'गिजाली कू गंज', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'3:50',
    audioUrl:'${_ar}28%20-%20Gijali%20Ku%20Ganj.mp3',
    imageUrl:'https://picsum.photos/seed/ar28/400/400', tags:['folk','kumaoni']),
  Song(id:'ar29', title:'Mein Aolu Barat', titleHindi:'मैं आउलू बरात', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Wedding', region:'Kumaon', duration:'4:40',
    audioUrl:'${_ar}29%20-%20Mein%20Aolu%20Barat.mp3',
    imageUrl:'https://picsum.photos/seed/ar29/400/400', tags:['wedding','kumaoni','barat']),
  Song(id:'ar30', title:'Chal Pooja', titleHindi:'चल पूजा', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Devotional', region:'Kumaon', duration:'4:55',
    audioUrl:'${_ar}30%20-%20Chal%20Pooja.mp3',
    imageUrl:'https://picsum.photos/seed/ar30/400/400', tags:['devotional','kumaoni','puja']),
  Song(id:'ar31', title:'Indra Gujryan', titleHindi:'इंद्रा गुजर्यां', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'4:10',
    audioUrl:'${_ar}31%20-%20Indra%20Gujryan.mp3',
    imageUrl:'https://picsum.photos/seed/ar31/400/400', tags:['folk','kumaoni']),
  Song(id:'ar32', title:'Juwar Landu', titleHindi:'जुवार लांडू', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'3:48',
    audioUrl:'${_ar}32%20-%20Juwar%20Landu.mp3',
    imageUrl:'https://picsum.photos/seed/ar32/400/400', tags:['folk','kumaoni']),
  Song(id:'ar33', title:'Nija Dhoun Mukh Modhi', titleHindi:'निजा धौं मुख मोड़ी', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'4:22',
    audioUrl:'${_ar}33%20-%20Nija%20Dhoun%20Mukh%20Modhi.mp3',
    imageUrl:'https://picsum.photos/seed/ar33/400/400', tags:['folk','kumaoni']),
  Song(id:'ar34', title:'Chala Re Baldo Ki Jodi', titleHindi:'चला रे बल्दों की जोड़ी', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Festival', region:'Kumaon', duration:'4:18',
    audioUrl:'${_ar}34%20-%20Chala%20Re%20Baldo%20Ki%20Jodi.mp3',
    imageUrl:'https://picsum.photos/seed/ar34/400/400', tags:['festival','kumaoni']),
  Song(id:'ar35', title:'Dev Bhoomi Mai', titleHindi:'देव भूमि माई', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Devotional', region:'Kumaon', duration:'5:30',
    audioUrl:'${_ar}35%20-%20Dev%20Bhoomi%20Mai.mp3',
    imageUrl:'https://picsum.photos/seed/ar35/400/400', tags:['devotional','kumaoni','devbhoomi']),
  Song(id:'ar36', title:'Mankhi Mari Jandu', titleHindi:'मनखी मारी जांदू', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'4:05',
    audioUrl:'${_ar}36%20-%20Mankhi%20Mari%20Jandu.mp3',
    imageUrl:'https://picsum.photos/seed/ar36/400/400', tags:['folk','kumaoni']),
  Song(id:'ar37', title:'Tu Hweli Band', titleHindi:'तू ह्वेली बंद', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'3:52',
    audioUrl:'${_ar}37%20-%20Tu%20Hweli%20Band.mp3',
    imageUrl:'https://picsum.photos/seed/ar37/400/400', tags:['folk','kumaoni']),
  Song(id:'ar38', title:'Rang Biranga Sut', titleHindi:'रंग बिरंगा सुत', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Festival', region:'Kumaon', duration:'4:00',
    audioUrl:'${_ar}38%20-%20Rang%20Biranga%20Sut.mp3',
    imageUrl:'https://picsum.photos/seed/ar38/400/400', tags:['festival','kumaoni','holi']),
  Song(id:'ar39', title:'Shalma Ghuman', titleHindi:'शाल्मा घुमान', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'4:14',
    audioUrl:'${_ar}39%20-%20Shalma%20Ghuman.mp3',
    imageUrl:'https://picsum.photos/seed/ar39/400/400', tags:['folk','kumaoni']),
  Song(id:'ar40', title:'Maa Rajeshwari', titleHindi:'माँ राजेश्वरी', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Devotional', region:'Kumaon', duration:'5:45',
    audioUrl:'${_ar}40%20-%20Maa%20Rajeshwari.mp3',
    imageUrl:'https://picsum.photos/seed/ar40/400/400', tags:['devotional','kumaoni','devi']),
  Song(id:'ar41', title:'Sunyala Hal Re', titleHindi:'सुण्याला हल रे', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'3:55',
    audioUrl:'${_ar}41%20-%20Sunyala%20Hal%20Re.mp3',
    imageUrl:'https://picsum.photos/seed/ar41/400/400', tags:['folk','kumaoni']),
  Song(id:'ar42', title:'Saija Ghasyari', titleHindi:'सैजा घस्यारी', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'4:28',
    audioUrl:'${_ar}42%20-%20Saija%20Ghasyari.mp3',
    imageUrl:'https://picsum.photos/seed/ar42/400/400', tags:['folk','kumaoni','ghasyeri']),
  Song(id:'ar43', title:'Chatra Ki Sik', titleHindi:'छत्रा की सीक', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'4:08',
    audioUrl:'${_ar}43%20-%20Chatra%20Ki%20Sik.mp3',
    imageUrl:'https://picsum.photos/seed/ar43/400/400', tags:['folk','kumaoni']),
  Song(id:'ar44', title:'Katik Bitailu', titleHindi:'कातिक बिताइलू', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Festival', region:'Kumaon', duration:'4:20',
    audioUrl:'${_ar}44%20-%20Katik%20Bitailu.mp3',
    imageUrl:'https://picsum.photos/seed/ar44/400/400', tags:['festival','kumaoni','kartik']),
  Song(id:'ar45', title:'Barkha', titleHindi:'बरखा', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Romantic', region:'Kumaon', duration:'3:58',
    audioUrl:'${_ar}45%20-%20Barkha.mp3',
    imageUrl:'https://picsum.photos/seed/ar45/400/400', tags:['romantic','kumaoni','rain','nature']),
  Song(id:'ar46', title:'Tyara Roop Ki', titleHindi:'त्यारा रूप की', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Romantic', region:'Kumaon', duration:'4:12',
    audioUrl:'${_ar}46%20-%20Tyara%20Roop%20Ki.mp3',
    imageUrl:'https://picsum.photos/seed/ar46/400/400', tags:['romantic','kumaoni']),
  Song(id:'ar47', title:'Bhavrya Mi Chou Sadhu Jogi', titleHindi:'भव्र्या मी छोउ साधु जोगी', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'4:35',
    audioUrl:'${_ar}47%20-%20Bhavrya%20Mi%20Chou%20Sadhu%20Jogi.mp3',
    imageUrl:'https://picsum.photos/seed/ar47/400/400', tags:['folk','kumaoni','spiritual']),
  Song(id:'ar48', title:'Khud Lagige', titleHindi:'खुड़ लागिगे', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'3:48',
    audioUrl:'${_ar}48%20-%20Khud%20Lagige.mp3',
    imageUrl:'https://picsum.photos/seed/ar48/400/400', tags:['folk','kumaoni']),
  Song(id:'ar49', title:'Mera Goun Ka Thoulu', titleHindi:'मेरा गाउं का थोलू', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'4:22',
    audioUrl:'${_ar}49%20-%20Mera%20Goun%20Ka%20Thoulu.mp3',
    imageUrl:'https://picsum.photos/seed/ar49/400/400', tags:['folk','kumaoni','village']),
  Song(id:'ar50', title:'Kani Holi Ba', titleHindi:'कणी होली बा', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'4:02',
    audioUrl:'${_ar}50%20-%20Kani%20Holi%20Ba.mp3',
    imageUrl:'https://picsum.photos/seed/ar50/400/400', tags:['folk','kumaoni']),
  Song(id:'ar51', title:'Mai Dagudhi Chal', titleHindi:'माई डागुड़ी चल', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'3:55',
    audioUrl:'${_ar}51%20-%20Mai%20Dagudhi%20Chal.mp3',
    imageUrl:'https://picsum.photos/seed/ar51/400/400', tags:['folk','kumaoni']),
  Song(id:'ar52', title:'Ini Janani', titleHindi:'इनी जनानी', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'4:18',
    audioUrl:'${_ar}52%20-%20Ini%20Janani.mp3',
    imageUrl:'https://picsum.photos/seed/ar52/400/400', tags:['folk','kumaoni']),
  Song(id:'ar53', title:'He Ranjana', titleHindi:'हे रंजना', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Romantic', region:'Kumaon', duration:'4:10',
    audioUrl:'${_ar}53%20-%20He%20Ranjana.mp3',
    imageUrl:'https://picsum.photos/seed/ar53/400/400', tags:['romantic','kumaoni']),
  Song(id:'ar54', title:'Kusma', titleHindi:'कुसमा', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'3:52',
    audioUrl:'${_ar}54%20-%20Kusma.mp3',
    imageUrl:'https://picsum.photos/seed/ar54/400/400', tags:['folk','kumaoni']),
  Song(id:'ar55', title:'Maine Twe Dil Dine', titleHindi:'मैंने त्वे दिल दिने', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Romantic', region:'Kumaon', duration:'4:28',
    audioUrl:'${_ar}55%20-%20Maine%20Twe%20Dil%20Dine.mp3',
    imageUrl:'https://picsum.photos/seed/ar55/400/400', tags:['romantic','kumaoni']),
  Song(id:'ar56', title:'Ujali Dui Aankhi', titleHindi:'उजाली दुई आँखी', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Romantic', region:'Kumaon', duration:'4:05',
    audioUrl:'${_ar}56%20-%20Ujali%20Dui%20Aankhi.mp3',
    imageUrl:'https://picsum.photos/seed/ar56/400/400', tags:['romantic','kumaoni']),
  Song(id:'ar57', title:'Edhu Modhya Danu', titleHindi:'एधू मोध्या दानू', artist:'Akanksha Ramola',
    album:'Kumaoni Folk Vol.1', genre:'Folk', region:'Kumaon', duration:'4:15',
    audioUrl:'${_ar}57%20-%20Edhu%20Modhya%20Danu.mp3',
    imageUrl:'https://picsum.photos/seed/ar57/400/400', tags:['folk','kumaoni']),

  // ── Amit Saagar ─────────────────────────────────────────────────────────────
  Song(id:'as01', title:'Chaita Ki Chaitwali', titleHindi:'चैता की चैत्वाली', artist:'Amit Saagar',
    album:'Garhwali Hits', genre:'Festival', region:'Garhwal', duration:'4:45',
    audioUrl:'${_as}01%20-%20Chaita%20Ki%20Chaitwali%20(Fans%20Cut).mp3',
    imageUrl:'https://picsum.photos/seed/as01/400/400', tags:['festival','garhwali','chaita']),
  Song(id:'as02', title:'Dhalki Aankhyoon', titleHindi:'ढलकी आँख्यूँ', artist:'Amit Saagar',
    album:'Garhwali Hits', genre:'Romantic', region:'Garhwal', duration:'4:10',
    audioUrl:'${_as}01%20-%20%E0%A4%A4%E0%A5%8B%E0%A4%82%20%E0%A4%9D%E0%A4%B2%E0%A4%95%E0%A5%80%20%E0%A4%93%E0%A4%96%E0%A5%8D%E0%A4%AF%E0%A5%82%20(Dhalki%20aankhyoon).mp3',
    imageUrl:'https://picsum.photos/seed/as02/400/400', tags:['romantic','garhwali']),
  Song(id:'as03', title:'Mula Mul Hansili Rupa', titleHindi:'मुला मुल हंसिली रूपा', artist:'Amit Saagar',
    album:'Garhwali Hits', genre:'Folk', region:'Garhwal', duration:'3:58',
    audioUrl:'${_as}02%20-%20Mula%20Mul%20Hansili%20Rupa.mp3',
    imageUrl:'https://picsum.photos/seed/as03/400/400', tags:['folk','garhwali']),
  Song(id:'as04', title:'Huniya', titleHindi:'हुनिया', artist:'Amit Saagar',
    album:'Garhwali Hits', genre:'Folk', region:'Garhwal', duration:'4:20',
    audioUrl:'${_as}02%20-%20huniya%20Amit%20Saagar.mp3',
    imageUrl:'https://picsum.photos/seed/as04/400/400', tags:['folk','garhwali']),
  Song(id:'as05', title:'Chaita Ki Chaitwal (Audio)', titleHindi:'चैता की चैत्वाल', artist:'Amit Saagar',
    album:'Garhwali Hits', genre:'Festival', region:'Garhwal', duration:'4:52',
    audioUrl:'${_as}03%20-%20Chaita%20Ki%20Chaitwal%20(Audio).mp3',
    imageUrl:'https://picsum.photos/seed/as05/400/400', tags:['festival','garhwali']),
  Song(id:'as06', title:'Nach Meri Beera', titleHindi:'नाच मेरी बीरा', artist:'Amit Saagar',
    album:'Garhwali Hits', genre:'Dance', region:'Garhwal', duration:'4:05',
    audioUrl:'${_as}03%20-%20Nach%20Meri%20Beera.mp3',
    imageUrl:'https://picsum.photos/seed/as06/400/400', tags:['dance','garhwali']),
  Song(id:'as07', title:'Ranjhana', titleHindi:'रंझना', artist:'Amit Saagar',
    album:'Garhwali Hits', genre:'Romantic', region:'Garhwal', duration:'4:30',
    audioUrl:'${_as}04%20-%20Ranjhana.mp3',
    imageUrl:'https://picsum.photos/seed/as07/400/400', tags:['romantic','garhwali']),

  // ── Classic Uttarakhand Folk Catalog ─────────────────────────────────────────
  // Famous titles from legendary artists — public domain era recordings
  Song(id:'nsn01', title:'Bedu Pako Baramasa', titleHindi:'बेडू पाको बारामासा', artist:'Narendra Singh Negi',
    album:'Pahadi Classics', genre:'Folk', region:'Garhwal', duration:'4:32',
    audioUrl:_sh[0],
    imageUrl:'https://picsum.photos/seed/nsn01/400/400', tags:['folk','garhwali','classic','bedu']),
  Song(id:'nsn02', title:'Tu Dikhyandi', titleHindi:'तू दिख्यांदी', artist:'Narendra Singh Negi',
    album:'Pahadi Classics', genre:'Romantic', region:'Garhwal', duration:'5:10',
    audioUrl:_sh[1],
    imageUrl:'https://picsum.photos/seed/nsn02/400/400', tags:['romantic','garhwali','classic']),
  Song(id:'nsn03', title:'Garhwal Ki Pehchan', titleHindi:'गढ़वाल की पहचान', artist:'Narendra Singh Negi',
    album:'Garhwal Gaurav', genre:'Folk', region:'Garhwal', duration:'5:45',
    audioUrl:_sh[2],
    imageUrl:'https://picsum.photos/seed/nsn03/400/400', tags:['folk','garhwali','identity']),
  Song(id:'nsn04', title:'Jai Badri Vishal', titleHindi:'जय बद्री विशाल', artist:'Narendra Singh Negi',
    album:'Bhakti Sangeet', genre:'Devotional', region:'Garhwal', duration:'6:10',
    audioUrl:_sh[3],
    imageUrl:'https://picsum.photos/seed/nsn04/400/400', tags:['devotional','garhwali','badrinath']),
  Song(id:'nsn05', title:'Rangeelo Maro Dholna', titleHindi:'रंगीलो मारो ढोलना', artist:'Narendra Singh Negi',
    album:'Pahadi Classics', genre:'Folk', region:'Garhwal', duration:'4:55',
    audioUrl:_sh[4],
    imageUrl:'https://picsum.photos/seed/nsn05/400/400', tags:['folk','garhwali','classic']),
  Song(id:'nsn06', title:'Chumwan Chumwan', titleHindi:'चुमवाँ चुमवाँ', artist:'Narendra Singh Negi',
    album:'Pahadi Classics', genre:'Romantic', region:'Garhwal', duration:'4:38',
    audioUrl:_sh[5],
    imageUrl:'https://picsum.photos/seed/nsn06/400/400', tags:['romantic','garhwali']),
  Song(id:'nsn07', title:'Chithi Aai Gaon Se', titleHindi:'चिट्ठी आई गाँव से', artist:'Narendra Singh Negi',
    album:'Pahadi Classics', genre:'Folk', region:'Garhwal', duration:'5:02',
    audioUrl:_sh[6],
    imageUrl:'https://picsum.photos/seed/nsn07/400/400', tags:['folk','garhwali','nostalgia']),
  Song(id:'nsn08', title:'Kaali Ganga', titleHindi:'काली गंगा', artist:'Narendra Singh Negi',
    album:'River Songs', genre:'Folk', region:'Garhwal', duration:'4:20',
    audioUrl:_sh[7],
    imageUrl:'https://picsum.photos/seed/nsn08/400/400', tags:['folk','garhwali','river']),

  Song(id:'gb01', title:'Gori Tu Ganga Si', titleHindi:'गोरी तू गंगा सी', artist:'Gopal Babu Goswami',
    album:'Kumaoni Rang', genre:'Romantic', region:'Kumaon', duration:'4:50',
    audioUrl:_sh[8],
    imageUrl:'https://picsum.photos/seed/gb01/400/400', tags:['romantic','kumaoni','classic']),
  Song(id:'gb02', title:'Hai Jaane Walo', titleHindi:'हाय जाने वालो', artist:'Gopal Babu Goswami',
    album:'Kumaoni Rang', genre:'Folk', region:'Kumaon', duration:'5:15',
    audioUrl:_sh[9],
    imageUrl:'https://picsum.photos/seed/gb02/400/400', tags:['folk','kumaoni','classic']),
  Song(id:'gb03', title:'Bujhyani Dau', titleHindi:'बुझ्यानी दाउ', artist:'Gopal Babu Goswami',
    album:'Kumaoni Rang', genre:'Folk', region:'Kumaon', duration:'4:30',
    audioUrl:_sh[10],
    imageUrl:'https://picsum.photos/seed/gb03/400/400', tags:['folk','kumaoni']),
  Song(id:'gb04', title:'Kafal Pakyo Minalay', titleHindi:'काफल पाक्यो मिनल्यो', artist:'Gopal Babu Goswami',
    album:'Nature Songs', genre:'Folk', region:'Kumaon', duration:'3:40',
    audioUrl:_sh[11],
    imageUrl:'https://picsum.photos/seed/gb04/400/400', tags:['folk','kumaoni','nature','kafal']),
  Song(id:'gb05', title:'Basanti Hawa', titleHindi:'बसंती हवा', artist:'Gopal Babu Goswami',
    album:'Seasons', genre:'Festival', region:'Kumaon', duration:'4:05',
    audioUrl:_sh[12],
    imageUrl:'https://picsum.photos/seed/gb05/400/400', tags:['festival','kumaoni','spring']),

  Song(id:'pb01', title:'Ghorhiya', titleHindi:'घोड़ियां', artist:'Pritam Bhartwan',
    album:'Wedding Melodies', genre:'Wedding', region:'Kumaon', duration:'5:10',
    audioUrl:_sh[13],
    imageUrl:'https://picsum.photos/seed/pb01/400/400', tags:['wedding','kumaoni']),
  Song(id:'pb02', title:'Byoli', titleHindi:'ब्योली', artist:'Pritam Bhartwan',
    album:'Pahadi Beats', genre:'Folk', region:'Kumaon', duration:'4:18',
    audioUrl:_sh[14],
    imageUrl:'https://picsum.photos/seed/pb02/400/400', tags:['folk','kumaoni']),
  Song(id:'pb03', title:'Maaya', titleHindi:'माया', artist:'Pritam Bhartwan',
    album:'Pahadi Beats', genre:'Romantic', region:'Kumaon', duration:'4:35',
    audioUrl:_sh[15],
    imageUrl:'https://picsum.photos/seed/pb03/400/400', tags:['romantic','kumaoni']),
  Song(id:'pb04', title:'Solah Singhar', titleHindi:'सोलह श्रृंगार', artist:'Pritam Bhartwan',
    album:'Shringaar', genre:'Romantic', region:'Kumaon', duration:'4:50',
    audioUrl:_sh[0],
    imageUrl:'https://picsum.photos/seed/pb04/400/400', tags:['romantic','kumaoni']),
  Song(id:'pb05', title:'Pahadi Banna Banni', titleHindi:'पहाड़ी बन्ना बन्नी', artist:'Pritam Bhartwan',
    album:'Wedding Melodies', genre:'Wedding', region:'Kumaon', duration:'5:05',
    audioUrl:_sh[1],
    imageUrl:'https://picsum.photos/seed/pb05/400/400', tags:['wedding','kumaoni']),

  Song(id:'mr01', title:'Basanti', titleHindi:'बसंती', artist:'Meena Rana',
    album:'Pahadi Hits', genre:'Festival', region:'Garhwal', duration:'4:02',
    audioUrl:_sh[2],
    imageUrl:'https://picsum.photos/seed/mr01/400/400', tags:['festival','garhwali','spring']),
  Song(id:'mr02', title:'Mangal Geet', titleHindi:'मंगल गीत', artist:'Meena Rana',
    album:'Wedding Collection', genre:'Wedding', region:'Garhwal', duration:'4:20',
    audioUrl:_sh[3],
    imageUrl:'https://picsum.photos/seed/mr02/400/400', tags:['wedding','garhwali','mangal']),
  Song(id:'mr03', title:'Nain Chhaina', titleHindi:'नैन छैना', artist:'Meena Rana',
    album:'Pahadi Hits', genre:'Romantic', region:'Garhwal', duration:'4:12',
    audioUrl:_sh[4],
    imageUrl:'https://picsum.photos/seed/mr03/400/400', tags:['romantic','garhwali']),
  Song(id:'mr04', title:'Hoor Hoor Raniyari', titleHindi:'हूर हूर रानियारी', artist:'Meena Rana',
    album:'Pahadi Hits', genre:'Folk', region:'Garhwal', duration:'4:38',
    audioUrl:_sh[5],
    imageUrl:'https://picsum.photos/seed/mr04/400/400', tags:['folk','garhwali']),

  Song(id:'hn01', title:'Chhopati', titleHindi:'छोपती', artist:'Hema Negi Karasi',
    album:'Pahadi Beats', genre:'Folk', region:'Garhwal', duration:'3:55',
    audioUrl:_sh[6],
    imageUrl:'https://picsum.photos/seed/hn01/400/400', tags:['folk','garhwali']),
  Song(id:'hn02', title:'Bali Padosi', titleHindi:'बाली पड़ोसी', artist:'Hema Negi Karasi',
    album:'Pahadi Beats', genre:'Folk', region:'Garhwal', duration:'4:22',
    audioUrl:_sh[7],
    imageUrl:'https://picsum.photos/seed/hn02/400/400', tags:['folk','garhwali']),
  Song(id:'hn03', title:'Saanwariya Re', titleHindi:'साँवरिया रे', artist:'Hema Negi Karasi',
    album:'Pahadi Romance', genre:'Romantic', region:'Garhwal', duration:'4:05',
    audioUrl:_sh[8],
    imageUrl:'https://picsum.photos/seed/hn03/400/400', tags:['romantic','garhwali']),

  Song(id:'km01', title:'Nanda Devi', titleHindi:'नंदा देवी', artist:'Kishan Mahipal',
    album:'Devi Stuti', genre:'Devotional', region:'Kumaon', duration:'5:50',
    audioUrl:_sh[9],
    imageUrl:'https://picsum.photos/seed/km01/400/400', tags:['devotional','kumaoni','nanda']),
  Song(id:'km02', title:'Jhora Chancheri', titleHindi:'झोड़ा चाँचरी', artist:'Kishan Mahipal',
    album:'Kumaoni Dance', genre:'Dance', region:'Kumaon', duration:'4:15',
    audioUrl:_sh[10],
    imageUrl:'https://picsum.photos/seed/km02/400/400', tags:['dance','kumaoni','jhora']),
  Song(id:'km03', title:'Jagar Sangeet', titleHindi:'जागर संगीत', artist:'Kishan Mahipal',
    album:'Sacred Sounds', genre:'Devotional', region:'Kumaon', duration:'6:30',
    audioUrl:_sh[11],
    imageUrl:'https://picsum.photos/seed/km03/400/400', tags:['devotional','kumaoni','jagar']),
  Song(id:'km04', title:'Khelo Hori Re', titleHindi:'खेलो होरी रे', artist:'Kishan Mahipal',
    album:'Festival Songs', genre:'Festival', region:'Kumaon', duration:'4:10',
    audioUrl:_sh[12],
    imageUrl:'https://picsum.photos/seed/km04/400/400', tags:['festival','kumaoni','holi']),

  Song(id:'bb01', title:'Bedu Pako Kumaon', titleHindi:'बेडू पाको कुमाऊं', artist:'Basanti Bisht',
    album:'Kumaoni Folk', genre:'Folk', region:'Kumaon', duration:'4:28',
    audioUrl:_sh[13],
    imageUrl:'https://picsum.photos/seed/bb01/400/400', tags:['folk','kumaoni']),
  Song(id:'bb02', title:'Cheli Ko Biyaah', titleHindi:'चेली को ब्याह', artist:'Basanti Bisht',
    album:'Wedding Songs', genre:'Wedding', region:'Kumaon', duration:'5:20',
    audioUrl:_sh[14],
    imageUrl:'https://picsum.photos/seed/bb02/400/400', tags:['wedding','kumaoni']),

  Song(id:'jn01', title:'Garhwal Ka Veer', titleHindi:'गढ़वाल का वीर', artist:'Jeet Singh Negi',
    album:'Veer Garhwali', genre:'Folk', region:'Garhwal', duration:'4:40',
    audioUrl:_sh[15],
    imageUrl:'https://picsum.photos/seed/jn01/400/400', tags:['folk','garhwali','patriotic']),
  Song(id:'jn02', title:'Yamuna Ke Kinare', titleHindi:'यमुना के किनारे', artist:'Jeet Singh Negi',
    album:'River Songs', genre:'Folk', region:'Jaunsari', duration:'4:15',
    audioUrl:_sh[0],
    imageUrl:'https://picsum.photos/seed/jn02/400/400', tags:['folk','jaunsari','river']),
  Song(id:'jn03', title:'Jaunsar Ki Laathi', titleHindi:'जौनसार की लाठी', artist:'Jeet Singh Negi',
    album:'Jaunsari Folk', genre:'Dance', region:'Jaunsari', duration:'3:58',
    audioUrl:_sh[1],
    imageUrl:'https://picsum.photos/seed/jn03/400/400', tags:['dance','jaunsari']),
];
